# Generated by Django 4.2.30 on 2026-04-08 14:10

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_audience', models.CharField(choices=[('CH', 'mixed ages 8-16 years'), ('AD', 'adults & late teens'), ('FA', 'children with adults')], max_length=2)),
                ('workshop_duration', models.IntegerField(verbose_name='Workshop duration (min)')),
                ('workshop_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cost pp (£)')),
            ],
            options={
                'ordering': ['target_audience'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('event_date', models.DateTimeField(unique=True)),
                ('location', models.CharField(default='on site', max_length=400)),
                ('excerpt', models.TextField(max_length=500)),
                ('full_description', models.TextField()),
                ('max_places', models.IntegerField(default=12)),
                ('primary_photo', cloudinary.models.CloudinaryField(default='placeholder_workshop', max_length=255, verbose_name='cover_image')),
                ('secondary_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='extra_image')),
                ('updated_on', models.DateField(auto_now=True)),
                ('publication_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Open'), (2, 'Cancelled'), (3, 'Closed')], default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='workshops.workshoptype')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
