# Generated by Django 6.0.4 on 2026-04-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopactivity',
            name='excerpt',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='workshopactivity',
            name='session_name',
            field=models.CharField(max_length=100),
        ),
    ]
