# Generated by Django 6.0.4 on 2026-04-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='session_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='workshoptype',
            name='target_audience',
            field=models.CharField(choices=[('CH', 'children'), ('AD', 'adults'), ('FA', 'families')], max_length=2),
        ),
    ]
