# Generated by Django 6.0.4 on 2026-04-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_alter_workshopactivity_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshop',
            options={'ordering': ['event_date']},
        ),
    ]
