# Generated by Django 6.0.4 on 2026-04-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_alter_workshop_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='low_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshop',
            name='tickets_sold',
            field=models.IntegerField(default=0),
        ),
    ]
