# Generated by Django 6.0.4 on 2026-04-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_workshop_low_stock_workshop_tickets_sold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshopactivity',
            options={'verbose_name_plural': 'workshop activities'},
        ),
    ]
