# Generated by Django 6.0.4 on 2026-05-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_alter_workshopactivity_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='secondary_photo',
        ),
    ]
