# Generated by Django 6.0.4 on 2026-04-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'messages'},
        ),
    ]
