# Generated by Django 4.2.30 on 2026-04-08 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_tickets', models.IntegerField(verbose_name='Number of adult places booked')),
                ('child_tickets', models.IntegerField(verbose_name='Number of child places booked')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('feedbackSubmitted', models.BooleanField(default=False)),
                ('additional_information', models.TextField(blank=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookee', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_to_attend', to='workshops.workshop')),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
    ]
