# Generated by Django 6.0.4 on 2026-04-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='adult_tickets',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='child_tickets',
        ),
        migrations.AddField(
            model_name='reservation',
            name='tickets',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
