# Generated by Django 6.0.4 on 2026-04-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_reservation_adult_tickets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='has_dietary_requirements',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='additional_information',
            field=models.TextField(blank=True, verbose_name="If 'yes' above, please give details of any allergies (eg. latose, gluten, nuts) or dietary requirements (eg. vegan, Halal, vegetarian)"),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='consent_given',
            field=models.BooleanField(default=False, verbose_name='I agree to the terms and conditions of booking and have supplied accurate information about the dietary needs and allergies for those attending'),
        ),
    ]
