# Generated by Django 6.0.4 on 2026-04-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_reservation_has_dietary_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='additional_information',
            field=models.TextField(blank=True, verbose_name="If 'no' above, please give details of any allergies (eg. latose, gluten, nuts) or dietary requirements (eg. vegan, Halal, vegetarian)"),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='has_dietary_requirements',
            field=models.BooleanField(default=False, verbose_name='None of those attending have specific dietary needs or allergies'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='tickets',
            field=models.IntegerField(verbose_name='Number of tickets to reserve'),
        ),
    ]
