# Generated by Django 6.0.4 on 2026-04-25 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_reservation_additional_information_and_more'),
        ('workshops', '0004_workshop_low_stock_workshop_tickets_sold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-workshop__event_date']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='additional_information',
            field=models.TextField(blank=True, verbose_name="If 'yes' above, please give details of any allergies (eg. latose, gluten, nuts) or dietary requirements (eg. vegan, Halal, vegetarian)"),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='has_dietary_requirements',
            field=models.BooleanField(default=False, verbose_name='Members of my booking have specific dietary needs or allergies'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop', to='workshops.workshop'),
        ),
    ]
