# Generated by Django 6.0.4 on 2026-04-27 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['workshop__event_date']},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='feedbackSubmitted',
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_rating', models.IntegerField(blank=True, choices=[(1, 'Terrible'), (2, 'Not as good as hoped'), (3, 'Average'), (4, 'Enjoyed it!'), (5, 'Absolutely brilliant!')])),
                ('feedback_comment', models.TextField(blank=True)),
                ('recommend', models.BooleanField(default=False, verbose_name='I would recommend this to others.')),
                ('updated_on', models.DateField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='bookings.reservation')),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
    ]
