# Generated by Django 6.0.4 on 2026-04-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_rating',
            field=models.IntegerField(choices=[(0, 'not specified'), (1, 'Terrible'), (2, 'Not as good as hoped'), (3, 'Average'), (4, 'Enjoyed it!'), (5, 'Absolutely brilliant!')], default=0),
        ),
    ]
