# Generated by Django 6.0.4 on 2026-04-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_feedback_submitted_alter_feedback_feedback_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-booking__workshop__event_date'], 'verbose_name_plural': 'feedback'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_rating',
            field=models.IntegerField(choices=[(0, 'not specified'), (1, 'Terrible'), (2, 'Disappointing'), (3, 'Average'), (4, 'Enjoyed it!'), (5, 'Brilliant!')], default=0),
        ),
    ]
